In [1]:
# !pip install --upgrade google-api-python-client

Collecting google-api-python-client
  Downloading https://files.pythonhosted.org/packages/56/04/5259a17a16a779426f6e2ac62796135b0d4a59cf8033a21037fd4ba5bf81/google_api_python_client-1.7.4-py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 3.4MB/s ta 0:00:01
Requirement already satisfied, skipping upgrade: uritemplate<4dev,>=3.0.0 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-api-python-client) (3.0.0)
Requirement already satisfied, skipping upgrade: httplib2<1dev,>=0.9.2 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-api-python-client) (0.10.3)
Requirement already satisfied, skipping upgrade: google-auth>=1.4.1 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-api-python-client) (1.5.1)
Requirement already satisfied, skipping upgrade: six<2dev,>=1.6.1 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-api-python-client) (1.10.0)
Requirement already satisfied, skipping upgrade: google-auth-httplib2>=0.0.3 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-api-python-client) (0.0.3)
Requirement already satisfied, skipping upgrade: rsa>=3.1.4 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-auth>=1.4.1->google-api-python-client) (3.4.2)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-auth>=1.4.1->google-api-python-client) (0.2.2)
Requirement already satisfied, skipping upgrade: cachetools>=2.0.0 in /usr/local/envs/py3env/lib/python3.5/site-packages (from google-auth>=1.4.1->google-api-python-client) (2.1.0)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /usr/local/envs/py3env/lib/python3.5/site-packages (from rsa>=3.1.4->google-auth>=1.4.1->google-api-python-client) (0.4.4)
Installing collected packages: google-api-python-client
  Found existing installation: google-api-python-client 1.6.2
    Uninstalling google-api-python-client-1.6.2:
      Successfully uninstalled google-api-python-client-1.6.2
Successfully installed google-api-python-client-1.7.4

In [26]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np
import math 

PROJECT = 'qwiklabs-gcp-aebfb78fe0f1b1d1' # REPLACE WITH YOUR PROJECT ID
BUCKET = 'sarah-bucket' # REPLACE WITH YOUR BUCKET NAME
REGION = 'us-central1' # REPLACE WITH YOUR BUCKET REGION e.g. us-central1
os.environ['TFVERSION'] = '1.7'  # Tensorflow version

SEQ_LEN = 50

### Define the project, Bucket and Region and set them.

In [3]:
# for bash
os.environ['PROJECT'] = PROJECT
os.environ['BUCKET'] = BUCKET
os.environ['REGION'] = REGION

In [4]:
%%bash
gcloud config set project $PROJECT
gcloud config set compute/region $REGION

Updated property [core/project].
Updated property [compute/region].

In [5]:
! pwd
! ls

/content/datalab/energy_forcasing/Sarah
ARIMA.csv		 data		  train_cloud_model.ipynb
BIG_q.ipynb		 Energy_ts	  trained
build_local_model.ipynb  hyperparam.yaml  train_local_model.ipynb
Build_model_task.ipynb	 sarah_data.csv
CNN_W2P_model		 test.json

In [6]:
CSV_COLUMNS = ['prediction_date', 'wind_speed_100m', 
  'wind_direction_100m', 
  'temperature', 
  'air_density',
  'pressure', 'precipitation', 'wind_gust', 'radiation', 
  'wind_speed', 'wind_direction', 'price']
FEATURES = CSV_COLUMNS[1:len(CSV_COLUMNS) - 1]
LABEL = CSV_COLUMNS[0]

df5 = pd.read_csv('/content/datalab/energy_forcasing/Sarah/sarah_data.csv', header = None, names = CSV_COLUMNS)
df5.describe()

,wind_speed_100m,wind_direction_100m,temperature,air_density,pressure,precipitation,wind_gust,radiation,wind_speed,wind_direction,price
count,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000,6646.000000
mean,4.799901,189.582975,14.920355,1.132338,935.286695,0.117364,4.872509,225.250182,3.220986,189.082629,50.153506
std,1.964154,58.126639,9.626527,0.039333,6.105083,0.245561,2.428587,266.299815,1.319704,56.712796,12.448392
min,1.372222,47.883333,-6.044444,1.036111,913.800000,0.000000,1.194444,0.000000,0.855556,50.538889,4.000000
25%,3.534722,142.598611,7.540278,1.106111,932.034722,0.000000,3.284722,0.000000,2.294444,143.750000,43.000000
50%,4.477778,191.908333,14.213889,1.131667,934.761111,0.000000,4.327778,95.000000,2.961111,191.208333,50.890000
75%,5.544444,232.043056,21.062500,1.160556,937.805556,0.100000,5.627778,416.422222,3.850000,230.865278,59.950000
max,15.044444,329.544444,41.044444,1.229444,961.238889,1.700000,16.705556,954.288889,9.738889,327.711111,85.050000

In [7]:
df2 = pd.read_csv('data/CNN_W2P_model/train-1.csv', header = None)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.948333,0.942500,0.912333,0.500000,0.781000,0.654167,0.808333,0.724833,0.992833,0.668833,...,0.658333,0.500000,1.085000,0.953333,0.500000,0.846000,0.784667,0.751667,0.247333,1.001667
1,0.942500,0.912333,0.500000,0.781000,0.654167,0.808333,0.724833,0.992833,0.668833,0.750000,...,0.500000,1.085000,0.953333,0.500000,0.846000,0.784667,0.751667,0.247333,1.001667,1.008333
2,0.912333,0.500000,0.781000,0.654167,0.808333,0.724833,0.992833,0.668833,0.750000,0.830833,...,1.085000,0.953333,0.500000,0.846000,0.784667,0.751667,0.247333,1.001667,1.008333,0.790500
3,0.500000,0.781000,0.654167,0.808333,0.724833,0.992833,0.668833,0.750000,0.830833,0.834500,...,0.953333,0.500000,0.846000,0.784667,0.751667,0.247333,1.001667,1.008333,0.790500,1.124667
4,0.781000,0.654167,0.808333,0.724833,0.992833,0.668833,0.750000,0.830833,0.834500,0.816667,...,0.500000,0.846000,0.784667,0.751667,0.247333,1.001667,1.008333,0.790500,1.124667,0.492167

In [8]:
df3 = pd.read_csv('data/CNN_W2P_model/valid-1.csv', header = None) #, names = CSV_COLUMNS)
df3.describe()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
count,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,...,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000,2638.000000
mean,0.827618,0.827851,0.827685,0.827717,0.827745,0.827840,0.827769,0.827687,0.827698,0.827717,...,0.829831,0.829818,0.829786,0.829823,0.829786,0.829683,0.829584,0.829590,0.829577,0.829446
std,0.217746,0.217454,0.217529,0.217534,0.217526,0.217463,0.217445,0.217395,0.217400,0.217403,...,0.215509,0.215509,0.215515,0.215481,0.215470,0.215397,0.215381,0.215381,0.215382,0.215333
min,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,...,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667
25%,0.707250,0.707542,0.707250,0.707250,0.707250,0.707542,0.707542,0.707542,0.707542,0.707542,...,0.710625,0.710625,0.710625,0.710625,0.710625,0.710625,0.710625,0.710625,0.710625,0.710625
50%,0.842167,0.842833,0.842167,0.842833,0.842833,0.842833,0.842167,0.842167,0.842167,0.842833,...,0.844917,0.844833,0.844833,0.844833,0.844833,0.844833,0.844167,0.844833,0.844833,0.844167
75%,0.995667,0.995667,0.995667,0.995667,0.995667,0.995667,0.995667,0.995125,0.995125,0.995125,...,0.995000,0.995000,0.995000,0.995000,0.995000,0.994958,0.994833,0.994833,0.994833,0.994833
max,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,...,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500,1.417500

This is where youre model lives and can be pushed out to the cloud.

In [9]:
! ls /content/datalab/energy_forcasing/Sarah/CNN_W2P_model/trainer

__init__.py  __init__.pyc  model.py  model.pyc	task.py

In [12]:
ls /content/datalab/energy_forcasing/Sarah/CNN_W2P_model/trained/cnn/export/exporter/

1537820821/

### Push out the training and evaluation data for the cloud
You can check to make sure the files were moved by looking in the "bucket" or "storage" and looking for the data files (.csv's in our case).

In [13]:
import shutil
shutil.rmtree('/data/CNN_W2P_model ', ignore_errors=True)
os.makedirs('/data/CNN_W2P_model/')

FileExistsError: [Errno 17] File exists: '/data/CNN_W2P_model/'

In [12]:
%bash
gsutil -m rm -rf gs://${BUCKET}/CNN_W2P_model/*
gsutil -m cp data/CNN_W2P_model/*.csv gs://${BUCKET}/CNN_W2P_model

CommandException: 1 files/objects could not be removed.
Copying file://data/CNN_W2P_model/to_model.csv [Content-Type=text/csv]...
Copying file://data/CNN_W2P_model/train-1.csv [Content-Type=text/csv]...
Copying file://data/CNN_W2P_model/valid-1.csv [Content-Type=text/csv]...
-
Operation completed over 3 objects/5.5 MiB.

### Push out to the cloud
After you run the code below - you can watch the process kick off and run on "ML Engine"

In [126]:
%%bash
for MODEL in linear dnn cnn rnn rnn2  ; do # rnnN
  OUTDIR=gs://${BUCKET}/CNN_W2P_model/${MODEL}
  JOBNAME=CNN_W2P_model_${MODEL}$(date -u +%y%m%d_%H%M%S)
  SEQ_LEN=50
  REGION=us-central1
  gsutil -m rm -rf $OUTDIR
  echo $JOBNAME
  gcloud ml-engine jobs submit training $JOBNAME \
     --region=$REGION \
     --module-name=trainer.task \
     --package-path=${PWD}/CNN_W2P_model/trainer \
     --job-dir=$OUTDIR \
     --scale-tier=PREMIUM_1 \
     --runtime-version=$TFVERSION \
     -- \
     --train_data_path="gs://${BUCKET}/CNN_W2P_model/train-1.csv" \
     --eval_data_path="gs://${BUCKET}/CNN_W2P_model/valid-1.csv"  \
     --output_dir=$OUTDIR \
     --train_steps=2000 --sequence_length=$SEQ_LEN --model=$MODEL
done

CNN_W2P_model_linear180924_201524
jobId: CNN_W2P_model_linear180924_201524
state: QUEUED
CNN_W2P_model_dnn180924_201528
jobId: CNN_W2P_model_dnn180924_201528
state: QUEUED
CNN_W2P_model_cnn180924_201532
jobId: CNN_W2P_model_cnn180924_201532
state: QUEUED
CNN_W2P_model_rnn180924_201535
jobId: CNN_W2P_model_rnn180924_201535
state: QUEUED
CNN_W2P_model_rnn2180924_201539
jobId: CNN_W2P_model_rnn2180924_201539
state: QUEUED

CommandException: 1 files/objects could not be removed.
Job [CNN_W2P_model_linear180924_201524] submitted successfully.
Your job is still active. You may view the status of your job with the command

  $ gcloud ml-engine jobs describe CNN_W2P_model_linear180924_201524

or continue streaming the logs with the command

  $ gcloud ml-engine jobs stream-logs CNN_W2P_model_linear180924_201524
CommandException: 1 files/objects could not be removed.
Job [CNN_W2P_model_dnn180924_201528] submitted successfully.
Your job is still active. You may view the status of your job with the command

  $ gcloud ml-engine jobs describe CNN_W2P_model_dnn180924_201528

or continue streaming the logs with the command

  $ gcloud ml-engine jobs stream-logs CNN_W2P_model_dnn180924_201528
CommandException: 1 files/objects could not be removed.
Job [CNN_W2P_model_cnn180924_201532] submitted successfully.
Your job is still active. You may view the status of your job with the command

  $ gcloud ml-engine jobs describe CNN_W2P_model_cnn180924_201532

or continue streaming the logs with the command

  $ gcloud ml-engine jobs stream-logs CNN_W2P_model_cnn180924_201532
CommandException: 1 files/objects could not be removed.
Job [CNN_W2P_model_rnn180924_201535] submitted successfully.
Your job is still active. You may view the status of your job with the command

  $ gcloud ml-engine jobs describe CNN_W2P_model_rnn180924_201535

or continue streaming the logs with the command

  $ gcloud ml-engine jobs stream-logs CNN_W2P_model_rnn180924_201535
CommandException: 1 files/objects could not be removed.
Job [CNN_W2P_model_rnn2180924_201539] submitted successfully.
Your job is still active. You may view the status of your job with the command

  $ gcloud ml-engine jobs describe CNN_W2P_model_rnn2180924_201539

or continue streaming the logs with the command

  $ gcloud ml-engine jobs stream-logs CNN_W2P_model_rnn2180924_201539

### Tensor Boards are finky and not always willing to run.  You can try in the window - or go back to the cloud shell and run the "command line access for TB."

In [15]:
from google.datalab.ml import TensorBoard
TensorBoard().start('gs://{}/CNN_W2P_model'.format(BUCKET))

24513

In [14]:
for pid in TensorBoard.list()['pid']:
  TensorBoard().stop(pid)
  print 'Stopped TensorBoard with pid {}'.format(pid)

NameError: name 'TensorBoard' is not defined

In [ ]:
## command line access of the TB
print('tensorboard --logdir=gs://{}/CNN_W2P_model --port=8083'.format(BUCKET))

## Deploy the model

### Convert the data into something that can be read into the model, so strings that are 49 long where the 50th price is perdicted.

In [47]:
# for bash
MODEL_CALL = 'linear'
MODEL_NAME = 'CNN_W2P_model'
MODEL_VERSION = 'ml_on_gcp'
os.environ['MODEL_NAME'] = MODEL_NAME
os.environ['MODEL_VERSION'] = MODEL_VERSION
os.environ['MODEL_CALL'] = MODEL_CALL

In [48]:
MODEL_LOCATION = 'gsutil ls gs://{}/{}/{}/export/exporter/ | tail -1'.format(BUCKET,MODEL_NAME,MODEL_CALL)
os.environ['MODEL_LOCATION'] = MODEL_LOCATION

In [49]:
%bash
gsutil ls gs://sarah-bucket/CNN_W2P_model/linear/export/exporter/

gs://sarah-bucket/CNN_W2P_model/linear/export/exporter/
gs://sarah-bucket/CNN_W2P_model/linear/export/exporter/1537820486/

In [50]:
print(MODEL_LOCATION)

gsutil ls gs://sarah-bucket/CNN_W2P_model/linear/export/exporter/ | tail -1

In [68]:
%bash
MODEL_NAME="CNN_W2P_model" ## you can name it w/e you want
MODEL_VERSION="ml_on_gcp"
MODEL_LOCATION=$(gsutil ls gs://${BUCKET}/CNN_W2P_model/linear/export/exporter/| tail -1)
echo "Deleting and deploying $MODEL_NAME $MODEL_VERSION from $MODEL_LOCATION ... this will take a few minutes"
#gcloud ml-engine versions delete ${MODEL_VERSION} --model ${MODEL_NAME}
#gcloud ml-engine models delete ${MODEL_NAME}
gcloud ml-engine models create ${MODEL_NAME} --regions $REGION
gcloud ml-engine versions create ${MODEL_VERSION} --model ${MODEL_NAME} --origin ${MODEL_LOCATION} --runtime-version $TFVERSION

ERROR: (gcloud.ml-engine.models.create) Resource in project [qwiklabs-gcp-aebfb78fe0f1b1d1] is the subject of a conflict: Field: model.name Error: A model with the same name already exists.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: A model with the same name already exists.
    field: model.name
ERROR: (gcloud.ml-engine.versions.create) unrecognized arguments:
  ls
  gs://sarah-bucket/CNN_W2P_model/linear/export/exporter/
  |
  tail
  -1

In [52]:
print('gsutil ls gs://{}/CNN_W2P_model/linear/export/exporter/ | tail -1'.format(BUCKET))

gsutil ls gs://sarah-bucket/CNN_W2P_model/linear/export/exporter/ | tail -1

Make data to feed to model

In [53]:
def to_csv(filename, start, N, J):
  with open(filename, 'w') as ofp:
    for ii in range(start, N):
      # nn = int(round(np.random.uniform(low = 0, high = 6466-J),0))
      seq = (df5.price[(ii):(ii+J)]/60) ## trade nn for ii to make an in seq dataset instead of random
      line = ",".join(map(str, seq))
      ofp.write(line + '\n')
      #print(len(seq))
      if len(seq) != J:
        break

import os
try:
  os.makedirs('data/CNN_W2P_model/')
except OSError:
  pass

to_csv('data/CNN_W2P_model/to_model', start = 0, N = 6596, J = 50) #  (6646 - 50) = 6596

In [54]:
model_data = pd.read_csv('/content/datalab/energy_forcasing/Sarah/data/CNN_W2P_model/to_model.csv', header = None)
model_data.shape

(6597, 49)

In [55]:
%%writefile test.json
{"price": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

Overwriting test.json

In [56]:
!pwd
!ls

/content/datalab/energy_forcasing/Sarah
ARIMA.csv		 data		  train_cloud_model.ipynb
BIG_q.ipynb		 Energy_ts	  trained
build_local_model.ipynb  hyperparam.yaml  train_local_model.ipynb
Build_model_task.ipynb	 sarah_data.csv
CNN_W2P_model		 test.json

In [60]:
from oauth2client.client import GoogleCredentials
import requests
import json

token = GoogleCredentials.get_application_default().get_access_token().access_token
print(token)
api = 'https://ml.googleapis.com/v1/projects/{}/models/{}/versions/{}:predict' \
         .format(PROJECT, MODEL_NAME, MODEL_VERSION)
print(api)
# headers = {'Authorization': 'Bearer ' + token }
# data = {
#   'instances': [
# {'price': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
#   ]
# }
# response = requests.post(api, json=data, headers=headers)
# print(response.content)

ya29.c.EloiBkDFJpCF7sX8SrlVUhTU26DcBpH70kQJSbwu9vD0jGiGGU1At6um3K05Uj-QqxSQNuPter1tohWnPBLVMronnBQORc6h-M7yaUSg0JZkHCrgNgETbgoGFXM
https://ml.googleapis.com/v1/projects/qwiklabs-gcp-aebfb78fe0f1b1d1/models/CNN_W2P_model/versions/ml_on_gcp:predict

In [93]:
## 55.11,62.0,46.79,44.0,44.0,44.86,60.89,58.69,36.49,57.69,51.2,48.79,48.35,42.2,46.37,62.5,62.5,54.0,52.54,62.18,48.5,55.35,52.0,40.97,42.6,64.1,61.59,48.9,37.4,45.93,37.3,65.48,62.5,65.03,57.07,23.35,54.56,28.02,39.84,51.0,42.46,47.02,37.1,38.0,38.0,60.99,50.01,19.52,39.98,47.96

This will take a few minutes.

In [95]:
#result = []
for y in range(1,10):#model_data.shape[0]):
    raw_prices = model_data.iloc[y]
    prices = [float(price) for price in raw_prices]
    #print prices
    data = {
      'instances': [
        {
          'price': prices
        },
      ]
    }
    #print(data)
    response = requests.post(api, json=data, headers=headers)
    #print y/model_data.shape[0]
    #forecast = response.json()['predictions'][0]['predicted'][0] ## (df5.price[(nn):(nn+J)])/60
    print (model_data.iloc[y], response.content[32:-4])
    #result.append(response.content[32:-4])

(0     56.55
1     54.74
2     30.00
3     46.86
4     39.25
5     48.50
6     43.49
7     59.57
8     40.13
9     45.00
10    49.85
11    50.07
12    49.00
13    43.69
14    63.03
15    45.59
16    53.56
17    38.12
18    55.89
19    40.16
20    65.10
21    39.58
22    59.85
23    55.00
24    64.19
25    53.28
26    68.60
27    41.00
28    39.25
29    38.35
30    55.76
31    40.32
32    62.59
33    46.78
34    49.85
35    59.69
36    56.00
37    65.10
38    58.69
39    39.50
40    30.00
41    65.10
42    57.20
43    30.00
44    50.76
45    47.08
46    45.10
47    14.84
48    60.10
Name: 1, dtype: float64, '0.838157057762146')
(0     54.74
1     30.00
2     46.86
3     39.25
4     48.50
5     43.49
6     59.57
7     40.13
8     45.00
9     49.85
10    50.07
11    49.00
12    43.69
13    63.03
14    45.59
15    53.56
16    38.12
17    55.89
18    40.16
19    65.10
20    39.58
21    59.85
22    55.00
23    64.19
24    53.28
25    68.60
26    41.00
27    39.25
28    38.35
29    55.76
30    40.32
31    62.59
32    46.78
33    49.85
34    59.69
35    56.00
36    65.10
37    58.69
38    39.50
39    30.00
40    65.10
41    57.20
42    30.00
43    50.76
44    47.08
45    45.10
46    14.84
47    60.10
48    60.50
Name: 2, dtype: float64, '0.838157057762146')
(0     30.00
1     46.86
2     39.25
3     48.50
4     43.49
5     59.57
6     40.13
7     45.00
8     49.85
9     50.07
10    49.00
11    43.69
12    63.03
13    45.59
14    53.56
15    38.12
16    55.89
17    40.16
18    65.10
19    39.58
20    59.85
21    55.00
22    64.19
23    53.28
24    68.60
25    41.00
26    39.25
27    38.35
28    55.76
29    40.32
30    62.59
31    46.78
32    49.85
33    59.69
34    56.00
35    65.10
36    58.69
37    39.50
38    30.00
39    65.10
40    57.20
41    30.00
42    50.76
43    47.08
44    45.10
45    14.84
46    60.10
47    60.50
48    47.43
Name: 3, dtype: float64, '0.838157057762146')
(0     46.86
1     39.25
2     48.50
3     43.49
4     59.57
5     40.13
6     45.00
7     49.85
8     50.07
9     49.00
10    43.69
11    63.03
12    45.59
13    53.56
14    38.12
15    55.89
16    40.16
17    65.10
18    39.58
19    59.85
20    55.00
21    64.19
22    53.28
23    68.60
24    41.00
25    39.25
26    38.35
27    55.76
28    40.32
29    62.59
30    46.78
31    49.85
32    59.69
33    56.00
34    65.10
35    58.69
36    39.50
37    30.00
38    65.10
39    57.20
40    30.00
41    50.76
42    47.08
43    45.10
44    14.84
45    60.10
46    60.50
47    47.43
48    67.48
Name: 4, dtype: float64, '0.838157057762146')
(0     39.25
1     48.50
2     43.49
3     59.57
4     40.13
5     45.00
6     49.85
7     50.07
8     49.00
9     43.69
10    63.03
11    45.59
12    53.56
13    38.12
14    55.89
15    40.16
16    65.10
17    39.58
18    59.85
19    55.00
20    64.19
21    53.28
22    68.60
23    41.00
24    39.25
25    38.35
26    55.76
27    40.32
28    62.59
29    46.78
30    49.85
31    59.69
32    56.00
33    65.10
34    58.69
35    39.50
36    30.00
37    65.10
38    57.20
39    30.00
40    50.76
41    47.08
42    45.10
43    14.84
44    60.10
45    60.50
46    47.43
47    67.48
48    29.53
Name: 5, dtype: float64, '0.838157057762146')
(0     48.50
1     43.49
2     59.57
3     40.13
4     45.00
5     49.85
6     50.07
7     49.00
8     43.69
9     63.03
10    45.59
11    53.56
12    38.12
13    55.89
14    40.16
15    65.10
16    39.58
17    59.85
18    55.00
19    64.19
20    53.28
21    68.60
22    41.00
23    39.25
24    38.35
25    55.76
26    40.32
27    62.59
28    46.78
29    49.85
30    59.69
31    56.00
32    65.10
33    58.69
34    39.50
35    30.00
36    65.10
37    57.20
38    30.00
39    50.76
40    47.08
41    45.10
42    14.84
43    60.10
44    60.50
45    47.43
46    67.48
47    29.53
48    43.52
Name: 6, dtype: float64, '0.838157057762146')
(0     43.49
1     59.57
2     40.13
3     45.00
4     49.85
5     50.07
6     49.00
7     43.69
8     63.03
9     45.59
10    53.56
11    38.12
12    55.89
13    40.16
14    65.10
15    39.58
16    59.85
17    55.00
18    64.19
19    53.28
20    68.60
21    41.00
22    39.25
23    38.35
24    55.76
25    40.32
26    62.59
27    46.78
28    49.85
29    59.69
30    56.00
31    65.10
32    58.69
33    39.50
34    30.00
35    65.10
36    57.20
37    30.00
38    50.76
39    47.08
40    45.10
41    14.84
42    60.10
43    60.50
44    47.43
45    67.48
46    29.53
47    43.52
48    28.07
Name: 7, dtype: float64, '0.838157057762146')
(0     59.57
1     40.13
2     45.00
3     49.85
4     50.07
5     49.00
6     43.69
7     63.03
8     45.59
9     53.56
10    38.12
11    55.89
12    40.16
13    65.10
14    39.58
15    59.85
16    55.00
17    64.19
18    53.28
19    68.60
20    41.00
21    39.25
22    38.35
23    55.76
24    40.32
25    62.59
26    46.78
27    49.85
28    59.69
29    56.00
30    65.10
31    58.69
32    39.50
33    30.00
34    65.10
35    57.20
36    30.00
37    50.76
38    47.08
39    45.10
40    14.84
41    60.10
42    60.50
43    47.43
44    67.48
45    29.53
46    43.52
47    28.07
48    56.95
Name: 8, dtype: float64, '0.838157057762146')
(0     40.13
1     45.00
2     49.85
3     50.07
4     49.00
5     43.69
6     63.03
7     45.59
8     53.56
9     38.12
10    55.89
11    40.16
12    65.10
13    39.58
14    59.85
15    55.00
16    64.19
17    53.28
18    68.60
19    41.00
20    39.25
21    38.35
22    55.76
23    40.32
24    62.59
25    46.78
26    49.85
27    59.69
28    56.00
29    65.10
30    58.69
31    39.50
32    30.00
33    65.10
34    57.20
35    30.00
36    50.76
37    47.08
38    45.10
39    14.84
40    60.10
41    60.50
42    47.43
43    67.48
44    29.53
45    43.52
46    28.07
47    56.95
48    47.89
Name: 9, dtype: float64, '0.838157057762146')